// Single source for plan data: rendered by components/Pricing.jsx (homepage
// and /pricing) and summarized into SoftwareApplication offers in lib/seo.js,
// so the structured data can never drift from the visible pricing.
// `amount` is the monthly USD figure (the Scale plan is a starting price).
export const tiers = [
  {
    id: 'starter',
    tier: 'Starter',
    kicker: 'Get help',
    name: 'The Support Sidekick',
    desc: 'For founders who are tired of answering the same customer questions.',
    price: '$49',
    amount: 49,
    per: '/month',
    founding: 'Founding price — limited founding spots',
    cta: 'Claim your founding spot →',
    href: 'https://app.tresolv.online',
    features: [
      '100 conversations per month',
      'Gmail + Shopify',
      'AI email support',
      'Live chat widget',
      'Live Shopify order lookup',
      'Shipping & tracking questions',
      'Product/order questions',
      'Returns & policy questions',
      'AI-drafted replies',
      'Human approval before replies/actions',
      'Confidence scoring',
      'Email quarantine / loop protection',
    ],
    quote: 'Let Luna handle the repetitive stuff. You handle the business.',
    featured: false,
    popular: false,
  },
  {
    id: 'growth',
    tier: 'Growth',
    kicker: 'Get out of the inbox',
    name: 'The AI Support Employee',
    desc: 'For Shopify brands ready to stop managing their inbox themselves.',
    price: '$99',
    amount: 99,
    per: '/month',
    founding: 'Founding price',
    cta: 'Claim your founding spot →',
    href: 'https://app.tresolv.online',
    plusNote: 'Includes everything in Starter, plus:',
    features: [
      '250 conversations per month',
      'Autopilot for high-confidence routine tickets',
      'Shopify action workflows',
      'Refund approval workflows',
      'Cancellation approval workflows',
      'Address-change workflows',
      'AfterShip live tracking',
      'Live storefront chat',
      'Customizable Luna identity',
      'Priority support',
    ],
    quote: 'Your AI support employee.',
    featured: true,
    popular: true,
  },
  {
    id: 'scale',
    tier: 'Scale',
    kicker: 'Build your support operation',
    name: 'The Support Department',
    desc: 'For brands where support is becoming a real operational bottleneck.',
    price: '$249',
    amount: 249,
    per: '/month+',
    founding: null,
    cta: 'Talk to us →',
    href: 'https://calendar.app.google/YkSqLTsYr18bUP2Z6',
    features: [
      'Higher/custom conversation volume',
      'Full autopilot where supported',
      'Shopify action execution with existing approval safeguards',
      'Custom integrations',
      'Custom agent identity/branding',
      'AfterShip',
      'Priority support',
      'Dedicated onboarding',
      'Custom SLA options',
    ],
    quote: "Your support team shouldn't be the reason you stop growing.",
    featured: false,
    popular: false,
  },
];
