import PageShell from '@/components/seo/PageShell';
import { buildMetadata } from '@/lib/seo';

export const metadata = buildMetadata({
  title: 'Privacy Policy | tResolv',
  description: 'How tResolv collects, uses, and protects merchant and customer data.',
  path: '/privacy',
});

export default function PrivacyPage() {
  return (
    <PageShell>
      <div className="privacy-hero">
        <h1>Privacy Policy</h1>
        <p>Last updated: 26 June 2026</p>
      </div>

      <div className="privacy-body">
        <div className="privacy-content">
          <h2>Who we are</h2>
          <p>tResolv is an AI-powered customer support tool for Shopify brands. We&apos;re based online at <a href="https://tresolv.online">tresolv.online</a>. If you have any questions about this policy, email us at <a href="mailto:syedahafsa722@gmail.com">syedahafsa722@gmail.com</a>.</p>

          <hr className="privacy-divider" />

          <h2>What we collect and why</h2>
          <p><strong>When you sign up as a merchant</strong>, we collect your email address and organisation name. We need this to create and manage your account.</p>
          <p><strong>When you connect Gmail</strong>, we access your support inbox to read incoming customer emails and send replies on your behalf. We only read emails in your inbox, nothing else in your Gmail account.</p>
          <p><strong>When you connect Shopify</strong>, we access order data (order number, items, status, customer name, shipping address) to help our AI give accurate answers to your customers.</p>
          <p><strong>Usage data</strong>: we collect basic analytics like ticket counts and resolution rates to help us improve the product and show you your dashboard stats.</p>

          <hr className="privacy-divider" />

          <h2>What we do not do</h2>
          <ul>
            <li>We do not sell your data or your customers&apos; data to anyone</li>
            <li>We do not use any data to train AI models</li>
            <li>We do not execute refunds, cancellations, or order changes without your explicit approval</li>
            <li>We do not read any Gmail emails outside your support inbox</li>
          </ul>

          <hr className="privacy-divider" />

          <h2>AI transparency</h2>
          <p>Every email reply sent by tResolv includes this footer: <em>&quot;This reply was generated by Luna, an AI assistant. Reply to speak with a human.&quot;</em></p>
          <p>This is required under UK GDPR and we think it&apos;s just the right thing to do.</p>

          <hr className="privacy-divider" />

          <h2>Who we share data with</h2>
          <p>We use a small number of trusted services to run tResolv:</p>
          <ul className="provider-list">
            <li><strong>Mistral AI</strong> (France, EU), powers our AI replies</li>
            <li><strong>Supabase</strong> (EU region), stores your account and ticket data</li>
            <li><strong>Google Gmail API</strong>, reads and sends emails via your connected account</li>
            <li><strong>Render.com</strong>, hosts our backend</li>
            <li><strong>Vercel</strong>, hosts our dashboard</li>
          </ul>
          <p>None of these providers are permitted to use your data for their own purposes.</p>

          <hr className="privacy-divider" />

          <h2>How long we keep data</h2>
          <p>Email content is automatically deleted after 90 days. Your account data is kept for as long as your account is active. When you disconnect tResolv, we delete your data within 30 days on request.</p>

          <hr className="privacy-divider" />

          <h2>Your rights (UK GDPR)</h2>
          <p>You have the right to access, correct, or delete your data at any time. Just email us at <a href="mailto:syedahafsa722@gmail.com">syedahafsa722@gmail.com</a> and we&apos;ll respond within 7 days.</p>

          <hr className="privacy-divider" />

          <h2>Lawful basis</h2>
          <p>We process support email data under <strong>legitimate interests</strong>, specifically, acting as a data processor on behalf of the merchant to provide the service they&apos;ve signed up for. Account data is processed under <strong>contract</strong>. We&apos;ve assessed that these interests do not override the rights of individuals whose data is processed.</p>

          <hr className="privacy-divider" />

          <h2>Changes to this policy</h2>
          <p>If we make significant changes, we&apos;ll notify merchants by email. Minor updates will just reflect a new &quot;last updated&quot; date at the top.</p>

          <div className="privacy-contact">
            <strong>Questions?</strong> Email us at <a href="mailto:syedahafsa722@gmail.com">syedahafsa722@gmail.com</a>
          </div>
        </div>
      </div>
    </PageShell>
  );
}
